#spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 8089
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/keepnotestep5
#    username: pooja_solanki
#    password: 6196solpoojA..
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 8089


server:
  port: 8089
spring:
  datasource:
    url : ${MYSQL_URL:jdbc:mysql://localhost:3306/keepnotestep5}
    username: ${MYSQL_USERNAME:pooja_solanki}
    password: ${MYSQL_PASSWORD:6196solpoojA..}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
