#spring:
#  data:
#    mongodb:
##      authentication-database: dbAdmin
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
#  application:
#    name: user-service
#server:
#  port: 8080
spring:
 data:
   mongodb:
     database: keepNoteStep5
     port: 27017
     host: localhost
 application:
   name: user-service
server:
 port: 9090



